
/**
 * @name 
 * @description 
 */
export type Req = {
  "studentOid": string
}
export type Res = {
  "body": {
    "artifactType": string,
    "commentCount": number,
    "createdAt": number,
    "creationRelease": {
      "checked": boolean,
      "coverGifLink": null,
      "coverLink": string,
      "createdAt": number,
      "customVersion": string,
      "description": string,
      "extensions": [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ],
      "hasCloudVariables": boolean,
      "keyboardLayout": string,
      "oid": string,
      "operatingInstruction": string,
      "profiling": null,
      "projectLink": string,
      "status": string,
      "submittedAt": number,
      "tags": [
        string
      ],
      "updatedAt": number,
      "version": string,
      "videoLink": null
    },
    "creationReleaseList": [
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      },
      {
        "checked": boolean,
        "coverGifLink": null,
        "coverLink": string,
        "createdAt": number,
        "customVersion": string,
        "description": string,
        "extensions": [
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string,
          string
        ],
        "hasCloudVariables": boolean,
        "keyboardLayout": string,
        "oid": string,
        "operatingInstruction": string,
        "profiling": null,
        "projectLink": string,
        "status": string,
        "submittedAt": number,
        "tags": [
          string
        ],
        "updatedAt": number,
        "version": string,
        "videoLink": null
      }
    ],
    "currentHashTag": null,
    "currentReleaseOid": string,
    "description": string,
    "eid": null,
    "ext": {
      "keyboardLayout": string,
      "requireLogin": boolean,
      "SUBMIT_HASH_TAGS": []
    },
    "favoriteCount": number,
    "featuredCoverLink": string,
    "firstPublishedRelease": {
      "checked": boolean,
      "coverGifLink": null,
      "coverLink": string,
      "createdAt": number,
      "customVersion": string,
      "description": null,
      "extensions": [
        string,
        string,
        string
      ],
      "hasCloudVariables": boolean,
      "keyboardLayout": string,
      "oid": string,
      "operatingInstruction": string,
      "profiling": null,
      "projectLink": string,
      "status": string,
      "submittedAt": number,
      "tags": [
        string
      ],
      "updatedAt": number,
      "version": string,
      "videoLink": null
    },
    "forEveryone": boolean,
    "hashTags": [],
    "isOpenSource": boolean,
    "isSelf": boolean,
    "isTeamwork": boolean,
    "keyboardLayout": string,
    "lastPassedAt": number,
    "latestCoverLink": string,
    "latestProjectLink": string,
    "likeCount": number,
    "oid": string,
    "operatedAt": number,
    "projectLastModifiedAt": null,
    "rank": string,
    "remixCreationOid": null,
    "remixedCount": number,
    "remixedCreation": null,
    "repostedSource": null,
    "requireLogin": boolean,
    "screenMode": string,
    "sourceOpenLevel": string,
    "stats": null,
    "status": string,
    "student": null,
    "studentOid": string,
    "tags": [],
    "teamMemberRespList": [],
    "teamworkStatus": null,
    "title": string,
    "type": string,
    "typicalProjectId": null,
    "updatedAt": number,
    "viewCount": number,
    "visibleScope": string
  },
  "code": string,
  "msg": null,
  "status": number
}
  